org.gradle.daemon=false
org.gradle.jvmargs=-Xmx2048m -XX:+UseSerialGC
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Override path check for non-ASCII characters in path (e.g. Đồ án)
android.overridePathCheck=true
# Fix Kotlin compiler bug on Windows when pub cache is on C: and project is on D:
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
